Q1="SELECT COUNT(id) FROM Movie WHERE year<2000;"
Q2="SELECT AVG(rank) FROM Movie WHERE year=1991;"
Q3="SELECT MIN(rank) FROM Movie WHERE year=1991;"
Q4="SELECT fname,lname from actor inner join cast on id=pid where mid=27;"
Q5="SELECT COUNT(mid) FROM ACTOR INNER JOIN CAST ON id=pid WHERE fname='Jon' AND lname='Dough';"
Q6="select distinct name from movie inner join cast on mid=id where name LIKE 'Young Latin Girls%' and (year between 2003 and 2006);"
Q7="select distinct fname,lname from director inner join moviedirector on director.id=did inner join movie on movie.id=mid where name like 'Star Trek%';"
Q8="select name from movie inner join moviedirector on `movie`.id=`moviedirector`.mid inner join cast on `cast`.mid=`movie`.id inner join director on `director`.id=`moviedirector`.did inner join actor on `actor`.id=`cast`.pid WHERE (`director`.fname ='Jackie (I)' and `actor`.fname='Jackie (I)') and (`director`.lname='Chan' and `actor`.lname='Chan') order by name asc;"
Q9="select fname,lname from director inner join moviedirector on director.id=moviedirector.did inner join movie on movie.id=moviedirector.mid where year=2001 group by director.id having count(mid)>=4 order by fname asc,lname desc;"
Q10="select distinct gender,count(gender) from actor group by gender  order by gender asc;"
Q11="select m1.name,m2.name,m1.rank,m1.year from movie m1 cross join movie m2 where m1.name!=m2.name and m1.year=m2.year and m1.rank=m2.rank order by m1.name asc limit 100;"
Q12="select fname,year,avg(rank) from actor inner join cast on actor.id=pid inner join movie on movie.id=mid group by year,actor.id order by fname asc,year desc limit 100;"
#Q13="select actor.fname,d.fname,avg(m.rank) from actor inner join cast c inner join movie m inner join director d inner join moviedirector md on actor.id==c.pid and m.id==c.mid and m.id==md.mid and d.id==md.did group by actor.id,d.id having count(md.mid)>=5 order by avg(rank) desc,d.fname asc,actor.fname desc limit 100;"
Q13="select `actor`.fname,`director`.fname,avg(`movie`.rank) from movie inner join moviedirector on `movie`.id=`moviedirector`.mid inner join cast on `movie`.id=`cast`.mid inner join director on `director`.id=`moviedirector`.did inner join actor on `actor`.id=`cast`.pid group by `actor`.id,`director`.id having count(`moviedirector`.mid)>=5 order by avg(rank) desc,`director`.fname asc,`actor`.fname desc limit 100;"
